//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPWebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAPWebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;Rowsets DateCreated=&quot;2016-07-19T16:15:13&quot; EndDate=&quot;2016-07-14T10:29:49&quot; StartDate=&quot;2016-07-14T10:29:49&quot; Version=&quot;15.0 SP4 Patch 0 (Apr 21, 2015)&quot;&gt;
        ///    &lt;Rowset&gt;
        ///        &lt;Columns&gt;
        ///            &lt;Column Description=&quot;&quot; MaxRange=&quot;1&quot; MinRange=&quot;0&quot; Name=&quot;SelesOrder&quot; SQLDataType=&quot;1&quot; SourceColumn=&quot;SelesOrder&quot;/&gt;
        ///            &lt;Column Description=&quot;&quot; MaxRange=&quot;1&quot; MinRange=&quot;0&quot; Name=&quot;Contract&quot; SQLDataType=&quot;1&quot; SourceColumn=&quot;Contract&quot;/&gt;
        ///            &lt;Column Description=&quot;&quot; MaxRange=&quot;1&quot; MinRa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testsructurexml {
            get {
                return ResourceManager.GetString("testsructurexml", resourceCulture);
            }
        }
    }
}
